[Variables]
VariableState=
VariableTrack=
VariableArtist=
VariableCover=
VariablePosition=
VariableDuration=
VariableProgress=

[MeasureTrack]
Measure=String
String=#VariableTrack#
DynamicVariables=1

[MeasureCombine]
Measure=Script
ScriptFile=#@#Scripts\MediaCombine.lua
OrderCount=#MediaOrderCount#
Order1=#MediaOrder1#
Order2=#MediaOrder2#
Order3=#MediaOrder3#
Order4=#MediaOrder4#
Order5=#MediaOrder5#
