[GooglePlayMusicMeasureState]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=State

[GooglePlayMusicMeasureStateButton]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=State
Substitute="0":"Play","1":"Pause","2":"Play"

[GooglePlayMusicMeasureTrack]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Title
Substitute="":"#NoTrackNameText#"

[GooglePlayMusicMeasureArtist]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Artist
Substitute="":"#NoArtistNameText#"

[GooglePlayMusicMeasureCover]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Cover
CoverPath=#@#Covers\GooglePlayMusic.png
Substitute="":"#@#Images\nocover.png"

[GooglePlayMusicMeasurePosition]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Position

[GooglePlayMusicMeasureDuration]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Duration

[GooglePlayMusicMeasureProgress]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Progress
