[GooglePlayMusicMeasureState]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=State

[GooglePlayMusicMeasureTrack]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Title
Substitute="":"#NoTrackNameText#"

[GooglePlayMusicMeasureArtist]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Artist
Substitute="":"#NoArtistNameText#"

[GooglePlayMusicMeasureCover]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Cover
CoverPath=#@#Covers\GooglePlayMusic.png
Substitute="":"#@#Images\nocover.png"

[GooglePlayMusicMeasurePosition]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Position

[GooglePlayMusicMeasureDuration]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Duration

[GooglePlayMusicMeasureProgress]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Progress
