[NowPlayingMeasureState]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=State

[NowPlayingMeasureTrack]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=TITLE
Substitute="":"#NoTrackNameText#"

[NowPlayingMeasureArtist]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=ARTIST
Substitute="":"#NoArtistNameText#"

[NowPlayingMeasureCover]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=COVER

[NowPlayingMeasurePosition]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Position

[NowPlayingMeasureDuration]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=DURATION

[NowPlayingMeasureProgress]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Progress
