[MeasureState]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=State

[MeasureStateButton]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=STATE
Substitute="0":"Play","1":"Pause","2":"Play"

[MeasureTrack]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=TITLE
Substitute="":"#NoTrackNameText#"

[MeasureArtist]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=ARTIST
Substitute="":"#NoArtistNameText#"

[MeasureCover]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=COVER

[MeasurePosition]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Position

[MeasureDuration]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=DURATION

[MeasureProgress]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Progress
