[Variables]
;mdi-resistor
IconCore=[\xfb1f]

;mdi-clock
IconClock=[\xf953]

;mdi-harddisk
IconDrive=[\xf2ca]

;mdi-texture
IconGraphic=[\xf50c]

;mdi-package-variant
IconMemory=[\f3d6]

;mdi-wifi-strength-4
IconNetwork=[\xf927]

;mdi-cogs
IconSettings=[\xf8d5]

;mdi-temperature-celcius
IconTemperature=[\xf504]

;mdi-timer
IconUptime=[\xf51b]


;mdi-calculator-variant
;IconCore=[\xfa99]

;mdi-clock-outline
;IconClock=[\xf150]

;mdi-calendar
;IconClock=[\xf0ed]

;mdi-floppy
;IconDrive=[\xf249]

;mdi-database
;IconDrive=[\xf1b8]

;mdi-memory
;IconGraphic=[\xf35b]

;mdi-buffer
;IconMemory=[\xf619]

;mdi-contain
;IconMemory=[\xfa3d]

;mdi-database
;IconMemory:[\xf1b8]

;mdi-memory
;IconMemory=[\xf35b]

;mdi-table-edit
;IconMemory=[\xf4f0]

;mdi-reorder-horizontal
;IconMemory=[\xf687]

;mdi-library-shelves
;IconMemory=[\xfb85]

;mdi-wifi
;IconNetwork=[\xf5a9]

;mdi-settings
;IconSettings=[\f493]

;mdi-fire
;IconTemperature=[\xf238]

;mdi-fan
;IconTemperature=[\xf210]

;mdi-thermometer
;IconTemperature=[\xf50f]

;mdi-temperature-fahrenheit
;IconTemperature=[\xf505]
