[Variables]
BackgroundColor=20202080
LabelColor=fc5c65
IconColor=f1f2f3
GraphColor=fc5c65
GraphTextColor=f0f0f090
TextColor=f1f2f3
BarBackgroundColor=20202050
BarFirstColor=e91e63
BarSecondColor=fc5c65
BarTextColor=f0f0f0f0
BarCaptionTextColor=a0a0a0f0

;BackgroundColor=ffffff
;ThemeColor=c0ca33
;TextColor=202020
;IconColor=f1f2f3

TextFont=Noto Sans CJK KR Regular
IconFont=Material Design Icons

; ================= USAGE MONITOR ==================
UsageBlacklist=_Total|Idle|dwm|wmpnetwk|csrss|svchost|lsass|System|system|Memory Compression|wininit|RemindersServer|spoolsv|IpOverUsbSvc|WmiPrvSE

; =================== DRIVE SKIN ===================
Drive1=C:
Drive2=G:

; MB/s
MaxDriveSpeed=20

; ================== WEATHER SKIN ==================
LocationCode=KSXX0027
Unit=m

TemperatureEnabled=1
