[Variables]
# Group 2xx: Thunderstorm
IconWeather200=[\xf593]
IconWeather201=[\xf67d]
IconWeather202=[\xf67d]
IconWeather210=[\xff4f]
IconWeather211=[\xf593]
IconWeather212=[\xf593]
IconWeather221=[\xf593]
IconWeather230=[\xf593]
IconWeather231=[\xf67d]
IconWeather232=[\xf67d]

# Group 3xx: Drizzle
IconWeather300=[\xff50]
IconWeather301=[\xf597]
IconWeather302=[\xf597]
IconWeather310=[\xf597]
IconWeather311=[\xf597]
IconWeather312=[\xf596]
IconWeather313=[\xf596]
IconWeather314=[\xf596]
IconWeather321=[\xf596]

# Group 5xx: Rain
IconWeather500=[\xff50]
IconWeather501=[\xf597]
IconWeather502=[\xf596]
IconWeather503=[\xf596]
IconWeather504=[\xf596]
IconWeather511=[\xf598]
IconWeather520=[\xf597]
IconWeather521=[\xf596]
IconWeather522=[\xf596]
IconWeather531=[\xf596]

# Group 6xx: Snow
IconWeather600=[\xff51]
IconWeather601=[\xf598]
IconWeather602=[\xff53]
IconWeather611=[\xf598]
IconWeather612=[\xf598]
IconWeather613=[\xff53]
IconWeather615=[\xf598]
IconWeather616=[\xf598]
IconWeather620=[\xf598]
IconWeather621=[\xff53]
IconWeather622=[\xff53]

# Group 7xx: Atmosphere
IconWeather701=[\xff4d]
IconWeather711=[\xff4d]
IconWeather721=[\xff4d]
IconWeather731=[\xf591]
IconWeather741=[\xf591]
IconWeather751=[\xf591]
IconWeather761=[\xf591]
IconWeather762=[\xf591]
IconWeather771=[\xf59e]
IconWeather781=[\xff55]

# Group 800: Clear
IconWeather800=[\xf599]

# Group 80x: Clouds
IconWeather801=[\xf595]
IconWeather802=[\xf595]
IconWeather803=[\xf590]
IconWeather804=[\xf590]
